version: '3.8'

services:
  app:
    build: .
    container_name: blog_app
    ports:
      - "3000:80"  # Map host port 3000 to container port 80
    restart: unless-stopped
    environment:
      - NODE_ENV=production